# Gradle Properties
org.gradle.jvmargs = -Xmx3G -Dfile.encoding=UTF-8

# Source Options
use_modern_java_syntax = false
use_lombok_ap = false
lombok_version = 1.18.46

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = false
show_testing_output = false

# Shadow
enable_shadow = false

# Mod Information
mod_version = mc1.12-r32
root_package = mods.flammpfeil.slashblade
reference_package = mods.flammpfeil.slashblade
mod_id = slashblade
mod_name = SlashBlade
archives_base_name = SlashBlade

# Mod Metadata
mod_description =
mod_url =
mod_update_json =
mod_authors = Ferne, zh_TW.lang-LostyBear, zh_CN.lang-Mrkwtkr
mod_credits = Furia
mod_logo_path =

# Catalogue Extra Metadata
mod_license =
mod_issue_tracker_url =
mod_icon_path =
mod_icon_item =
mod_background_path =

# Run Configurations
minecraft_username = Developer
extra_jvm_args =

# Maven Publishing
publish_to_maven = false
publish_to_local_maven = false
maven_name = ${mod_name}
maven_url =

# Access Transformers
use_access_transformer = true
access_transformer_locations = slashblade_at.cfg

# Mixins
use_mixins = false
mixin_booter_version = 10.6

# Coremods
is_coremod = false
coremod_includes_mod = true
coremod_plugin_class_name =

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5

# ConfigAnyTime
use_config_any_time = false
config_any_time_version = 3.0
